### ISSUE TITLE
Page Visibility API 章节关于页面卸载的想法

### ISSUE THREAD

**Issue by ZhongJinMing** [wangdoc/webapi-tutorial#13]
文章第五点有以下观点：
由此可见，`visibilitychange` 事件比 `pagehide`、`beforeunload`、`unload` 事件更可靠，所有情况下都会触发（从 `visible` 变为 `hidden`）。因此，可以只监听这个事件，运行页面卸载时需要运行的代码，不用监听后面那三个事件。
甚至可以这样说，`unload` 事件在任何情况下都不必监听，`beforeunload` 事件只有一种适用场景，就是用户修改了表单，没有提交就离开当前页面。另一方面，指定了这两个事件的监听函数，浏览器就不会缓存当前页面。

我的观点：`visibilitychange` 事件似乎不能替代 `unload` 事件，因为 `visibilitychange` 事件没办法确定页面什么时候卸载，而有些操作是必须在卸载前做的，比如 log 记录或者安全退出之类的。

**Comment by ruanyf** [comment]
这部分写得确实不好，需要重新梳理。但是现在没时间，先不改了
